### ISSUE TITLE
Admin UI port # in Read.me is wrong

### ISSUE THREAD

**Issue by zeroactive** [fluree/fluree-docker-example#1]
I believe the port number for the Admin UI in the Read.me, listed as 8090, is wrong.  This port # would work if you were inside the container, but in the docker-compose.cluster.yml file 8090 gets mapped to 8091 (line 6:   "- 8091:8090", so from your desktop you have to hit "http://localhost:8091" to reach the admin UI.

**Comment by cap10morgan** [comment]
@zeroactive Thanks. This repo is actually deprecated in favor of our official Docker image: https://hub.docker.com/repository/docker/fluree/ledger

We should update the README in here to that effect and mark the repo as archived.

**Comment by cap10morgan** [comment]
Actually, upon a closer look I realize that my colleague @jakep36 updated this to be a current and useful example of using docker-compose and your issue is relevant to the cluster example. Thanks, I'll get this fixed!
