### ISSUE TITLE
Unsupported config option for services: 'fluree-n1'

### ISSUE THREAD

**Issue by nothingalike** [fluree/fluree-docker-example#3]
When following the readme, I ran the `docker compose up` and got the following error

```bash
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
Unsupported config option for services: 'fluree-n1'
```

**Comment by cap10morgan** [comment]
@nothingalike What version of docker-compose are you using on what OS / version?

**Comment by nothingalike** [comment]
@cap10morgan you nailed it. the computer I'm on is quite out of date. just tried on a more active machine with everything up to date and i got the node up and running! 

Thank you
